### ISSUE TITLE
Native?

### ISSUE THREAD

**Issue by Sajjon** [CityOfZion/coz-neo-mobile-wallet#1]
What about developing a native iOS app in Swift?

**Comment by totalvm** [comment]
@Sajjon I might eventually switch over to react-native, for now this works fine with the limited time I have.
The IOS version works so i don't want to break it for now.

**Comment by Sajjon** [comment]
@totalvm I was thinking about fully native app in Swift. I am a decent Swift programmer. Would be nice with a fully native Swift code base :) any thoughts?

**Comment by totalvm** [comment]
@Sajjon 
I'd rather keep 1 code base for Android and IOS, since I don't own any apple products making something that can easily be used on both suits me better.

Of course you are free to make your own wallet
